---
- name: Atualiza pacotes........
  yum:
    state: latest
    name: '*'
    update_cache: true
- name: Instala pacotes
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - net-tools
    - vim
    - curl
    - nmap
    - tree
- name: Copiando arquivos de backup 
  copy: src=backup.tar.xz dest=/tmp/   #POR PADRÃO O ANSIBLE PROCURA NO DIRETÓRIO FILES DA ESTRUTURA
...
#comando usado na execução:
#ansible-playbook -i hosts ./tasks/main.yml

